areas_of_activity:
  - Education
  - Healthcare
  - Environment
  - Human Rights
  - Animal Welfare
  - Arts and Culture
  - Sports
  - Research and Development
  - International Development
  - Child Protection
  - Disaster Relief
  - Poverty Alleviation
  - Social Justice
  - Refugee Support
  - Gender Equality
  - Community Development
  - Public Safety
  - Senior Support
  - Youth Development
  - Public Policy

desired_impact_on:
  - Recruitment
  - Marketing
  - Brand Awareness
  - Corporate Social Responsibility (CSR)
  - Environmental, Social, Governance (ESG)
  - Employee Engagement
  - Innovation
  - Risk Management
  - Product Development
  - Customer Loyalty
  - Social Impact
  - Public Relations

operating_in:
  - Dolnośląskie
  - Kujawsko-Pomorskie
  - Lubelskie
  - Lubuskie
  - Łódzkie
  - Małopolskie
  - Mazowieckie
  - Opolskie
  - Podkarpackie
  - Podlaskie
  - Pomorskie
  - Śląskie
  - Świętokrzyskie
  - Warmińsko-Mazurskie
  - Wielkopolskie
  - Zachodniopomorskie
